create_dmd_release/create_dmd_release.d

- needed for CMD support in dlang.org's win32.mak

need backslashes for DMD path on Windows

---

windows/d2-installer.nsi

Update link to latest version. 
There might be another version (mostly to update the parser to adjust to new D syntax), but I don't know if it will be ready before the dmd release.

bump Visual D version to 0.3.40

---

windows/d1-installer.nsi
windows/d2-installer.nsi

Currently, the uninstaller will nuke the entire D installation directory, including any potential user files or files edited by the user.
Ideally we should only delete the files that we have installed, if they have not been modified.
For now, at least, warn users that we are going to delete everything.

Windows installer: Warn before nuking the entire D installation

---

windows/d2-installer.nsi

- skip message box when uninstaller is called with /S for silent

fix Issue 14864 - windows uninstall during installation pops up spurious warning

---

create_dmd_release/common.d
create_dmd_release/create_dmd_release.d

[Issue 14897 – shared linux libraries from zip package don't work](https://issues.dlang.org/show_bug.cgi?id=14897)

fix Issue 14897 - shared linux libraries from zip package don't work

---

create_dmd_release/build_all.d
create_dmd_release/create_dmd_release.d

[Issue 13889 – mscoff32 libs not available](https://issues.dlang.org/show_bug.cgi?id=13889)

fix Issue 13889 - mscoff32 libs not available

---

windows/d2-installer.nsi

this bug always makes me nervous because I usually use a changed folder and the uninstaller shows the default one. 
https://issues.dlang.org/show_bug.cgi?id=13234
also reuses old installation path from uninstall folder as default, reported in
https://issues.dlang.org/show_bug.cgi?id=12276

Fix issue 13234: when updating, uninstaller reports wrong installation directory

---

create_dmd_release/build_all.d

http://d.darktech.org/libcurl-7.44.0-WinSSL-zlib-x86-x64.zip
MD5: 1f550d0485dc156e87628db49f4896e3
Please upload it to http://downloads.dlang.org/other/
This libcurl.dll has been compiled with -DENABLE_IPV6
Fix https://issues.dlang.org/show_bug.cgi?id=15066

Update libcurl-7.44.0 - fix 15066

---

linux/dmd_deb.sh
linux/dmd_rpm.sh

- supported since many years
- binaries will be much smaller (about 50%)

use xz compression for .deb/.rpm packages

---

windows/d2-installer.nsi

there is an infinite loop when no SDK is detected
https://issues.dlang.org/show_bug.cgi?id=15284

fix Issue 15284 - dmd installer hangs when updating installed windows version 

---

script/install.sh

- installs requested dmd/gdc/ldc versions
and dub to a user-wide path (~/dlang) and
writes sourceable files to activate them
- installs itself to ~/dlang/install.sh
and can later be used to install/uninstall/list
compilers or update the script itself
- writes no file outside of the root path, so
a simple `rm -rf ~/dlang` removes everything
- only requires bash, curl, and xz

installer script

---

windows/ReplaceInFile.nsh

don't use temp folder to modify sc.ini to keep inheriting permissions
Bugzilla entries are https://issues.dlang.org/show_bug.cgi?id=15456 and https://issues.dlang.org/show_bug.cgi?id=15572

Fix issues 15456 and 15572 - bad sc.ini permissions for restricted users

---

script/install.sh

- newer versions of libarchive have builtin support for xz

correctly detect liblzma/xz support on OSX

---

script/install.sh

Not sure how many people have older 10.8/9 OSX versions without tar.xz support, but it's nice to provide some helpful information.

installation hint for OSX xz package

---

linux/dmd_deb.sh

- fixes the problem that dmd currently installs a complete X11 server
- only needed for browser/desktop related functionality, e.g. dman, or
std.phobos.brower open, it's OK when those don't work on a headless server

move xdg-utils from Depends to Suggests

---

script/install.sh

- curl's --retry option isn't really helpful b/c no timeouts are
activated by default
- use a retry loop with increasing sleep times instead
- enable connection (5s) and download (<1KB/s for 30s) timeouts
(using --max-time is too tricky b/c of the unknown download sizes)

fix Issue 16349 - better curl retry for install.sh script

---

script/install.sh

- allow to source the activate script with set -u

fix unbound bash variables in activate script

---

script/install.sh

Small follow-up on #1437 - I assume if you (@MartinNowak) thought that downloading DMD would be the default action, it's a good justification to make it so. On the other hand showing a help page if no command is provided is a good style, but I assume that this script is mostly only executed directly from the web or in CI scripts (and `-h` | `--help` still exists).
Btw [Rust](https://www.rust-lang.org/en-US/downloads.html) also downloads the compiler by default.

Download DMD by default

---

script/install.sh

Seems like #200 broke the ability to download/install point releases as it tries to query for the latest build version. This just extends the ignore regex to add point releases
CC @MartinNowak

Fix installation of dmd point releases

---

.travis.yml
travis.sh

As seen with #200 it's probably not a bad idea to enable CI for this repo ;-)
This adds a very simple bash script that tests basic install / uninstall features (by simply installing them and checking the output of `-version`).
I didn't add a check for the latest version (default command) as this obviously changes.
A non-D environment on Travis was selected on purpose, of course.
Would someone with admin rights be so kind to enable this project for Travis?
(it [passes](https://travis-ci.org/wilzbach/installer) on my fork)

Enable simple TravisCI testing

---

create_dmd_release/create_dmd_release.d
linux/dmd_deb.sh
linux/dmd_rpm.sh

- build amd64 linux libraries with PIC (no significant overhead of RIP relative
addressing)
- add -fPIC to default args on amd64

fix Issue 16794 - .deb no working on Ubuntu 16.10

---

script/install.sh

- running printf before calling the old prompt function did overwrite
the latest command status, use printf 'new prompt %s' (old_prompt)
to fix evaluation order

preserve latest status in prompt

---

script/install.sh

DUB is provided by DMD (>= 2.072.0) and LDC (>= 1.1.0), so there's no need to download it again.

Check whether DUB is provided by the release

---

script/install.sh

Reverts dlang/installer#214
A few issues popped up.

Revert "Check whether DUB is provided by the release"

---

windows/d2-installer.nsi

Would be nice to have the latest version of Visual D in the upcoming installer.

bump Visual D version to 0.44.2

---

windows/d2-installer.nsi

Needs https://github.com/dlang/dmd/pull/6716
See https://issues.dlang.org/show_bug.cgi?id=17280 and https://issues.dlang.org/show_bug.cgi?id=17320

Windows: add detection of VS 2017

---

create_dmd_release/patches/tools.patch

- disables building of docs/d-tags.json prerequistite for dman on WIn
- release docs are only built on Linux and copied to all other OSes
- timestamps should work but are somewhat unreliable (granularity)

fix patch for tools repo

---

create_dmd_release/build_all.d

- stop overwriting dmd's VERSION file for release building
and instead verify that it matches the gitTag
- -dirty flag of git describe was caused by
newline mismatch in VERSION file

fix Issue 17805 - -dirty flag on dmd's version

---

create_dmd_release/build_all.d

- an update_libs.bat script to regenerate omf import libs from a
Windows SDK is contained in the .zip archive and will be shipped
as dmd2/windows/lib/update_libs.bat as well
update_libs.bat
```bat
if -%1-==-- echo Missing Windows SDK folder argument & exit /b
:: CTL3D32 is missing in Windows SDK
:: Uuid is a static library in Windows SDK
for %%l in (COMCTL32.LIB CTL3D32.LIB ODBC32.LIB OLEAUT32.LIB WS2_32.LIB advapi32.lib comdlg32.lib gdi32.lib glu32.lib kernel32.lib ole32.lib opengl32.lib rpcrt4.lib shell32.lib user32.lib uuid.lib version.lib wininet.lib winmm.lib winspool.lib wsock32.lib) do coffimplib %1\%%l %%l
```
As the script comment says, CTL3D32.DLL is no longer present and Uuid.lib is now a static library, so those 2 remain in their current state.
Also see [COFFIMPLIB - Digital …

fix 6625 - update OMF import libraries

---

script/install.sh
travis.sh

> Also seems to fail, at least during initial installation, due to return 1 and set -e (errexit).
Can't reproduce this. Added tests for it to let Travis verify this.
> Mmh, this still queries code.dlang.org when a compiler is already installed.
Added a check. My main motivation was really just to avoid unnecessary downloads on Travis 
>> You also didn't adopt the activate scripts to work w/o a separate dub installation.
> It still "worked", because of the $PATH variable.
Now the `dub` folders shouldn't been written to the `activate` scripts anymore.
> I'll revert this for now to not impact any usage.
Sorry about that :/

Check for dub

---

windows/d2-installer.nsi

This PR attempts to silence the installer when the /S option is passed. The installer opens messages boxes in certain circumstances. Most of them are just informative and do not actually require user intervention. For example, one of them occurs when no VS is installed and asks whether it should automatically install VS2013.
This obviously prevents fully automated and unattended installations of dmd using this installer. I've stumbled upon this because I'm currently setting up such a scenario and tried using that installer on a fresh Window install.
I have to say, however, that I was not able to build and test the installer myself because I didn't find documentation on how to set it up or even how to begin... So I'm kind of providing this change "blindly". I'd be glad to test the …

Attempt to make windows installer more silent when /S is given

---

create_dmd_release/create_dmd_release.d

See also: https://github.com/dlang/dmd/pull/7669

Copy the generated man pages to the release archive

---

script/install.sh

Failures are getting more frequent, see e.g. https://github.com/travis-ci/travis-build/pull/1282
This is a first step at adding more mirrors.

Use fallback mirrors in the install script

---

create_dmd_release/create_dmd_release.d

It has always been bothering me that the windows installer also added configuration files for solaris, osx and others.

restrict installed configuration files to current OS

---

create_dmd_release/create_dmd_release.d
windows/d2-installer.nsi

- Chmgen and the d.chm Windows file are unreasonably unreliable
there were 4 issues responsible for 39 failing nightly builds in
2016, which are very time-consuming to debug and fix.
It seems that the basic approach to parse the html docs into
structured information is flawed and not sustainable.
- chm files are nice for offline usage, but it's a very minor tool
on which we spent a very unproportionate amount of resources.
- dman doesn't even offer offline capabilities, and can be easily
replaced by a browser shortcut to dlang.org's search field.
Also https://github.com/dlang/dlang.org/pull/2212 and https://forum.dlang.org/post/alcerzuvydfutsiuelsk@forum.dlang.org.

temporarily remove chmgen (d.chm, dman) from release

---

.travis.yml
appveyor.yml
windows/build_mingw.bat
windows/mingw/buildsdk.d
windows/mingw/msvcrt_abs.asm
windows/mingw/msvcrt_atexit.c
windows/mingw/msvcrt_data.c
windows/mingw/msvcrt_stub.c
windows/mingw/oldnames.c

includes https://github.com/dlang/tools/pull/267

Build mingw COFF libraries

---

create_dmd_release/build_all.d
create_dmd_release/create_dmd_release.d
windows/d2-installer-descriptions.nsh
windows/d2-installer.nsi
windows/makefile
windows/vcinstall.ini

- add mingw libraries to installation
- add installer page to select VS installation
- no need to patch sc.ini as dmd detects VS
@MartinNowak You will still have to add lld-link.exe to the extra folders.
The additional page only appears if no VS installation is detected and looks like this:

Windows installer: install mingw libs and improve VS selection

---

create_dmd_release/build_all.d

- old-dmd is fairly new by now and comes with everything necessary to
build a release, updating the old release could introduce weird
issues as it's not really tested
- directly extract libs and bins to extraBins folder that gets packed
into the release archive

stop overwriting old-dmd with new libs and binaries

---

script/install.sh

In the retry loop, `if` will exit prematurely if the retry body exits with `0`.
```bash
for i in {0..4}; do
if "$@"; then
break
```
Hence, `return 1` needs to be used.
This is a bit hard to test and would require to use e.g. a custom vibe.d server that doesn't respond for the first X times called (similar to the `fetchzip` test at DUB).
If this is wanted, I can look into adding this, but for now it would be great to deploy this as apparentely the `gdc` is rather unstable.

Use return 1 in the mirror retry body to stay in the retry loop

---

script/install.sh

As https://github.com/dlang/installer/pull/218 doesn't seem to be moving forward, I have uploaded all DUB releases to GitHub, which should be much more reliable (see https://github.com/dlang/dub/issues/1290 for details).
At the moment, there isn't a mirror for `code.dlang.org/download/LATEST` (we should probably create a gh-pages repo like LDC or use an S3 bucket), so for now I simply used the GitHub API. I know that it's rate-limited, but imho having a chance to succeed is a lot better than having none.
If code.dlang.org is down, we still manage to get the latest DUB:
```
dmd-2.077.1 already installed
curl: (7) Failed to connect to code.dlang.org port 80: Connection refused
curl: (7) Failed to connect to code.dlang.org port 80: Connection refused
curl: (7) Failed to connect to …
```

Use a fallback mirror for code.dlang.org

---

windows/mingw/buildsdk.d

these symbols do not exist for Win32 and are still missing in the 6.0 branch for mingw: https://sourceforge.net/p/mingw/mingw-org-wsl/ci/6.0-exp/tree/wslapi/lib/
mingw-w64 has them (https://github.com/mirror/mingw-w64/blob/master/mingw-w64-crt/lib-common/user32.def.in#L849) but basing the generation on a different distro is not (yet) reasonable.

Issue 19051 - Undefined functions Set/GetWindowLongPtr in mingw libs

---

script/install.sh

because not everywhere has gnu tools (e.g. macOS)

less gnu-y alternative to find -printf

---

script/install.sh

The problem was introduced in https://github.com/dlang/installer/pull/239 and presumable copied in https://github.com/dlang/installer/pull/218

fix uninitialised suffix on macOS

---

.gitignore
script/deploy.sh

- gitignore of the signature file
- remove the old signature file, s.t. gpg can't silently fail and we don't notice
- cd to ROOT, s.t. we can run the script from anywhere

Minor install script deploy improvements

---

script/install.sh
travis.sh

In case the user deleted it manually, the installer should detect this.

Install the keyring if it's missing

---

create_dmd_release/build_all.d

- to workaround occasional lost connections when fetching sth.
from the Windows VM

retry scp on Windows

---

script/deploy.sh
script/install.sh
travis.sh

- replace all nightlies.dlang.org URLs with downloads.dlang.org/nightlies
- quite some changes due to losing an alternative HTTPS download source
- rewrite dmd-2018-10-14 to dmd-master-2018-10-14 in the script so to
not clutter the download page with plenty of confusing symlinks

update install.sh script for new ddo nightlies

---

.travis.yml

According to https://github.com/travis-ci/travis-ci/issues/4895#issuecomment-150703192o
To avoid issues like https://github.com/dlang/installer/pull/335 or https://github.com/dlang/installer/pull/334

Use language:generic for Travis builds

---

script/install.sh

Tested for DMD (the error message) and LDC on x86_64 and aarch64 machines.
(couldn't test for GDC because that appears to be already broken for x86)

Add AArch64 support

---

script/install.sh
travis.sh

This PR installs ldc-nightly in e.g. "ldc-8c0abd52-20171222"
(DMD installs nightlies in e.g. "dmd-master-2017-12-27")
LDC does not have a LATEST_NIGHTLY file online, so I opted for just downloading the nightlies release page and grepping for what the binary package name should look like.
Tested on OSX.

Add 'ldc-nightly' install target

---

create_dmd_release/build_all.d

- to workaround infrequent OSX boot failure
- see e.g. https://buildkite.com/dlang/build-release/builds/234#e3736130-2407-4f48-b656-e81a0e86f851/6-12097

retry booting OSX box

---

windows/mingw/msvcrt_stub.c

This should fix the issues in https://forum.dlang.org/thread/uxmbtqqdomrrsnrssapc@forum.dlang.org.
I've tested linking the following DLL (with LDC), as both x86/x64 and with both msvcrt100.lib (2010) and vcruntime140.lib (2015), and it works:
```D
import core.sys.windows.windows;
extern(Windows) BOOL DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
{
return FALSE;
}
export void foo()
{
import core.stdc.stdlib : malloc, free;
auto blub = malloc(1024);
free(blub);
}
```

MinGW-w64 libs: Fix DLL entry point

---

windows/build_curl.bat

disable the workaround introduced in https://github.com/curl/curl/commit/72d5e144fbc6a9db264ae425bb788af218f25d9e
as it is causing the issue and the curl developers were not really convinced
disabled by defining DONT_USE_RECV_BEFORE_SEND_WORKAROUND when compiling curl

fix issue 20120 - libcurl.dll hangs when running std.net.curl unittests

---

create_dmd_release/build_all.d
create_dmd_release/create_dmd_release.d

This relies on https://github.com/dlang/dmd/pull/10468 for an updated sc.ini and optlink.exe being available in the "old" dmd (shipped since 2.079).

remove link.exe from installation, use optlink.exe instead

---

create_dmd_release/build_all.d

Just noticed that the release build fails due to link.exe no longer existing. Does the build actually use the latest rc to rebuild itself?
@MartinNowak Sorry for the trouble.

remove link.exe/optlink.exe from the old compiler only if they exist

---

.travis.yml
changelog/install-sh-windows.dd
script/install.sh
test/t/base.sh
test/t/dub.sh

Supports installing Windows binaries of DMD, LDC, and Dub on Windows, including nightlies, when running in POSIX-like environments such as MSYS.
Tests pass under MSys2 and CygWin for me.

script/install.sh: Add initial Windows support

---

script/install.sh

Unzipping a Windows `.zip` using a Posix `unzip` produces the warning `.zip appears to use backslashes as path separators`. This is harmless and should not cause the script to terminate. It occurs when `install.sh` is run in MSYS2 if 7z is not installed.

Don't panic on unzip warnings.

---

script/install.sh

Properly handle path arguments in Windows format like `-p %APPDATA%\dlang`. Without this conversion, an initial invocation of `\msys64\usr\bin\bash.exe -l %APPDATA%\dlang\install.sh -p %APPDATA%\dlang ldc` will fail with "gpg: invalid key resource URL 'C:\Users\me\AppData\Roaming\dlang/d-keyring.gpg'".

Properly handle path arguments in Windows format.

---

changelog/mingw-6.dd
create_dmd_release/build_all.d

Upgrade the installer to use the Mingw 6 definitions from https://github.com/dlang/installer/pull/346.
Would be great if someone can give this a quick test, s.t. we can ship with with the upcoming 2.086 beta.
This could fix:
- https://issues.dlang.org/show_bug.cgi?id=19773

Upgrade MinGW to 6.0.0

---

.azure-pipelines/build-lld.yml
azure-pipelines.yml
windows/build_lld.bat

dmd expects lld-link.exe in the same directory, so build an appropriate version for the bin64 folder.

build LLD for x64, too

---

create_dmd_release/build_all.d

it's an embarrassment to have this 24 years old version still distributed.
https://dlang.org/windbg.html should be removed, too. It doesn't seem to be referenced from anywhere else but the sitemap. https://dlang.org/dmd-windows.html contains a reference to https://digitalmars.com/d/2.0/windbg.html, though, the D language site from 2011!

remove windbg from installation

---

create_dmd_release/extras/windows/dmd2/windows/bin/README.TXT

This file uses tabs which seems to make the diff look weird. The normal file view has all columns aligned.

README.TXT: remove windbg, add missing tools

---

windows/d2-installer.nsi

This reduces the size of the installer from 26 MB to 24 MB.

Windows installer: increase compressor dictionary size for smaller installer

---

windows/d2-installer.nsi
windows/vcinstall.ini

VS2013 should probably removed, too, but I plan a couple of more changes to that page anyway (mostly not linking to the VC2010 redistributables, but just putting the DLLs into the bin folders).

Windows installer: update proposed downloads from VS2017 to VS2019

---

windows/build_lld.bat

patch LLD to not set IMAGE_DLL_CHARACTERISTICS_NO_SEH, the MS linker also doesn't do this.

fix Issue 20421 - Exceptions don't work when linking through lld-link

---

create_dmd_release/create_dmd_release.d

I suspect that this isn't done deliberately, as no other tools have debug information compiled in.
The Windows build shrinks from almost 11 MB to about 3 MB. The linux binary will probably have even more debug info (binary size is currently 20 MB compared to other tools at 2-4 MB).

do not build dub with debug info

---

windows/build_mingw.bat
windows/mingw/buildsdk.d
windows/mingw/msvcrt_stub.c

So that the user/druntime can use the wide `wmain` / `wWinMain` C entry points too.

MinGW-based libs: Add wide entry points

---

windows/d2-installer.nsi

`ReserveFile` inside a section doesn't seem to work

Windows installer: "reserve" files to avoid pauses when switching between pages

---

create_dmd_release/build_all.d

There has to be an lld-link.exe alongside dmd.exe in the bin64 folder anyway. Follow up to https://github.com/dlang/installer/pull/419

Windows: add 64-bit lld to bin64 folder

---

create_dmd_release/build_all.d
create_dmd_release/create_dmd_release.d
windows/build_release.bat

What's not optimal is that the LDC-built version gets only limited coverage in the dmd tests, only the win32-ldc pipeline.

build dmd.exe with LDC

---

create_dmd_release/build_all.d
create_dmd_release/create_dmd_release.d
windows/build_release.bat

- use vcvarsall.bat to setup correct compiler environment
(rather than explicitly including things)
- set CC, AR, LIB, and CC32 to plain command names
(leaving it to vcvarsall.bat to resolve them)
- BuildTools 2019 would fail to execute on Windows 7
(might miss some updates)

update to MSVC BuildTools 2017

---

changelog/windows.dd
create_dmd_release/create_dmd_release.d

otherwise, dub never uses the 64-bit version of dmd, even if first on the PATH.

Windows: add 64-bit build of dub.exe

---

windows/d2-installer-descriptions.nsh
windows/d2-installer.nsi

- remove description for dropped dmd1 download section
- build unicode instead of deprecated ansi installer

fix NSIS installer warnings

---

create_dmd_release/create_dmd_release.d

- fixup for dlang/druntime#3026

merge stable

---

changelog/install_sh_windows.dd
script/install.sh

The `install.sh` compiler version manager no longer requires running a POSIX terminal emulator. When run from the Windows command prompt it installs compilers in `%USERPROFILE%\dlang` and provides `activate.bat` for amending `PATH`.

Support install.sh being called from Windows cmd.

---

windows/d2-installer.nsi

"replace by" is the passive form (e.g., "A was replaced by B"), but it's used in two active sentences in the Windows installer.

Fix grammar error on Windows

---

create_dmd_release/build_all.d
create_dmd_release/create_dmd_release.d

Would no longer build due to changes in druntime mach-o headers.
Hasn't been tested since quite a while and is officially no longer supported anyhow ([Change Log: 2.085.0 - D Programming Language](https://dlang.org/changelog/2.085.0.html#osx-32bit)).

remove broken and unmaintained OSX-32 builds from releases

---

script/install.sh

Currently sourcing `activate` several times in a row (either for the same version or different versions) messes things up. With this the `deactivate` function clears the current activation before entering the new one.

Make the activate generated script reentrant

---

script/install.sh

The assumption that $SHLVL increases when the script is run does not always hold. $SHLVL does not increase if the script is piped into bash, thereby failing to detect Posix. Also, if the default terminal shell is not bash, $SHLVL might be 1 on Posix.

Fixes issue 21059: installer fails when piped on Posix.

---

script/install.sh
test/t/double_install.sh

`deactivate` for the previous installation was called after the new
deactivation handler has been registered.

Fix wrong deactivation in chained activation

---

script/install.sh

@wilzbach based on the https://github.com/dlang/dlang.org/pull/2817 discussion

add auto-update for the d-keyring

---

.azure-pipelines/build-winrelease.yml
azure-pipelines.yml
changelog/ldc_built_releases.md
create_dmd_release/build_all.d
create_dmd_release/common.d
create_dmd_release/create_dmd_release.d
windows/build_release.bat

- curl no longer needed for dlang.org as docs are build on linux
- use current libcurl (the one to be released)
- drop custom binaries being copied from previous release
- use ldc to build release
- setup VC environment to build create_dmd_release on Windows
- update to debian 9 (stretch)
- add changelog entry

build binary releases with LDC

---

create_dmd_release/create_dmd_release.d

run `git clean` instead of `make clean` to have platform independent cleanup
restore original VERSION file to avoid `git describe` returning "dirty" due to a previous build
@MartinNowak I cannot really test with just the Windows build. I suspect the problem only occurs due to the folder being shared by the different VMs.

fix issue 20620 - dmd version has -dirty suffix

---

script/install.sh
test/t/base.sh

I uploaded signatures files until 2.060. I doubt anyone is using older DMD installations on their CI.
After all, it even fails to run here on TravisCI.

Issue 21226 - Support installing older DMD versions

---

changelog/install-dmd-dc.dd
script/install.sh
test/common.sh
test/t/where.sh

This has come up frequently in the past.
Use case: one has a generic compiler variable like `$DMD` in a CI script and wants to use the install script without activating the environment.
See also:
- https://github.com/dlang/dmd/pull/7848#issuecomment-364235083
- https://github.com/dlang/tools/pull/297/files#diff-f9a62833538ab14fff849c2be16ab986R9
I'm not fully convinced about the name, so bike-shedding is allowed.
An alternative to this would have been to add a flag similar to `-a|--activate`.
That would require a two line change and would be fine for me too.
CC @WebDrake

Add '--dmd' and '--dc' to print the path of the installed compiler

---

create_dmd_release/build_all.d

I uploaded the binaries to downloads.dlang.org as well (though we don't need to do this anymore as we fetch it directly from the GitHub release).
See https://github.com/dlang/installer/pull/474 for details.

[build_all.d] Upgrade MinGW-based lib binaries to v8.0.0

---

create_dmd_release/build_all.d

Allows `build_all.d` to build only a selection of targets passed via the command line.

build_all.d: Add platform selection via command line

---

linux/dmd_deb.sh
linux/dmd_rpm.sh

All other parts of dmd have been covered.  It's just the installer dmd.conf that is preventing all _compiled_ 32-bit programs from segfaulting.

fix Issue 21488 - Bundled 32-bit dlang tools (ddemangle, dustmite, rdmd) segfault on startup

---

create_dmd_release/create_dmd_release.d

LTO isn't always plain sailing but let's try it.
A box & whisker plot of phobos test suite build times vs. flags

Fix Issue 18362 - Try to enable lto for all dmd builds

---

create_dmd_release/create_dmd_release.d

Only append the required `LIB` path s.t. the remaining values match the expected defaults from dmd. Required because the generated config contains an invalid `LINKCMD` with the new default for 32 bit windows.
Also changes the `tools` build to use host compiler to avoid issues w.r.t. the OMF => MsCoff default transition (as LDC defaults to MsCoff for 32).
---
Extracted from #494

Retain original sc.ini instead of generating a new one

---

.github/workflows/build_release_template.yml
.github/workflows/test_release.yml
create_dmd_release/create_dmd_release.d

This action is based off the dmd nightlies but also includes some required changes to make it available as a reuseable workflow. This allows actual workflows to call this template, e.g. for pull requests against this repository.
Also includes a test action that uses the new action & verifies the packaged compiler by building and running some basic program.
Note: The windows checks are partially disabled due to an upstream issue
(invalid `sc.ini` due to the Win32 OMF => MSCOFF change).
Includes the following changes to restore the currently broken release build:
- Disables LTO for FreeBSD because the generated DMD segfaults immediatly
- Provides custom DFLAGS when building the tools because the defaults found in `posix.mak` assume a freshly built dmd regardless of the actual `DMD`. …

Add a template to build releases on Github Actions

---

.github/workflows/build_release_template.yml

The build script currently requires an existing VS 2019 installation. But `windows-latest` allows for runners with `windows-2022` which have VS 2022 installed.
---
Not sure why runs from my fork consistently used `windows-2019` runners.

build_release_template: Use windows-2019 instead of windows-latest

---

.github/workflows/build_release_template.yml
.github/workflows/test_release.yml

`actions/checkout` defaults to the repository + branch that triggered the build, not where the action is defined. They are not set explicitly based on workflow parameters s.t. the defaults can be override for e.g. pull requests.
---
Noticed the problem when trying to redirect the nightly build to `build_release_template` - the build failed because it cloned `dmd` instead of `installer`.

Explicitly specify repo + branch when cloning installer

---

create_dmd_release/create_dmd_release.d
test/release/validate_release.sh

Defining `-version=DefaultCompiler_DMD` ensures that rdmd defaults to DMD instead of the current host compiler (LDC).
See dlang/tools#442
CC @CyberShadow @rikkimax

Enforce DMD as the default compiler for rdmd

---

create_dmd_release/create_dmd_release.d

Removes the overhead for multiple make instances and enables parallel builds.

Build tools in a single make instance

---

azure-pipelines.yml

The current image `vs2017-win16` is due for removal.
@maxhaton

Fix 22958 - Bump azure image to windows-2019

---

.azure-pipelines/build-winrelease.yml
.github/workflows/build_release_template.yml
create_dmd_release/create_dmd_release.d

So that we get all error messages, and for nightlies,
we can still publish the other releases if we want to.

Disable fail-fast on build-all-releases & fix nightlies

---

create_dmd_release/build_all.d

- RC2-40-CBC algo now in legacy provider
(see openssl/openssl#12227)

fix failing codesign cert fingerprint

---

create_dmd_release/build_all.d

- scp globbing no longer supported
- disable codesign by default (due to expired and excessively expensive EV certificates)

fixes for release building

---

create_dmd_release/build_all.d
create_dmd_release/create_dmd_release.d

- temporarily disable LTO on OSX to workaround dated linker :disappointed:
- scp with OSX requires target folders to exist before recursive copy
- workaround dated OSX sshd host key algos
We have to get 2.100.2 out and don't want to defer the build any longer. LTO for OSX was sometimes disabled beforehand.
LTO support in the dated linker/OSX image has been a gamble for quite a while.
This will be fixed by moving the build process to a CI system with up-to-date OSX/XCode.

fix OSX build issues

---

.github/workflows/build_release_template.yml
.github/workflows/test_release.yml

Github is removing 10.15 soon.  Bumped the related actions to their latest versions, to ensure that they work with newer versions of macOS hosts.

[github] Bump FreeBSD VM host image to macOS-12

---

script/install.sh

This is using our new downloads bucket, the old s3 bucket is there for archive only (no longer receiving any updates).

Use downloads.dlang.org instead of amazonaws for secondary mirror

---

.azure-pipelines/build-winrelease.yml
.github/workflows/build_release_template.yml
create_dmd_release/build_all.d
script/install.sh
windows/build_mingw.bat
windows/d2-installer.nsi

This is now possible now the site now has a new front for its bucket.

Update downloads.dlang.org links to use https

---

create_dmd_release/build_all.d
create_dmd_release/create_dmd_release.d

The old release builds were being built on a 10.8 machine, I've now ported it across to a 10.13 machine.  Still old, but not so much so that we have to build differently to Linux/Windows anymore.

Remove workarounds for old OSX release image

---

.github/workflows/build_release_template.yml

Building on ubuntu-latest may result in more recent libraries being linked in. E.g. currently dub nightly build fails to run dub-master because it depends on glibc 2.32+ while ubuntu-20.04 only has 2.31.

Build the Linux release on Ubuntu 20.04

---

.cirrus.yml
script/deploy.sh
test/common.sh
test/t/base.sh
test/t/dub.sh
test/t/where.sh

We seem to have missed the memo saying that the Intel-based runners will be removed from 1st Jan 2023, no idea if we are even ready to run on M1 hosts?
https://cirrus-ci.org/blog/2022/11/08/sunsetting-intel-macos-instances/

ci: Update cirrus macOS image to macos-monterey-xcode

---

test/release/validate_release.sh

As I understand, dub now has a more central build/cache location.  This just paints over the problem, but would keep compat with old and new behaviour.

test: Don't complain if .dub directory doesn't exist

---

create_dmd_release/create_dmd_release.d

Typically, git-clone probes the filesystem to see if it handles the executable bit correctly and the `core.fileMode` variable is automatically set as necessary. However when building dmd releases using vagrant box method, git-clone is done on a Linux host (i.e a filesystem that handles the filemode correctly), then scp'd to a Windows VM (i.e an environment that loses the filemode). So when building Windows binaries, always ensure this variable is set to `false`.

Fix Issue 22212 - dmd version has -dirty suffix on windows

---

.github/workflows/build_release_template.yml
.github/workflows/test_release.yml
create_dmd_release/build_all.d
create_dmd_release/create_dmd_release.d

Depends on
* https://github.com/dlang/dmd/pull/15894 and https://github.com/dlang/dmd/pull/15920
* https://github.com/dlang/phobos/pull/8862
* https://github.com/dlang/tools/pull/465
Soft depends on
* https://github.com/dlang/installer/pull/566 
The Windows VM used for the releases needs a GNU make; `mingw32-make.exe` is available for CI (the first `make.exe` in PATH there is DigitalMars make), so I went with that for now. FWIW, I've just seen that GNU make can also be installed via Chocolatey (`choco install make`).

Adapt to generic Makefiles

---

.github/workflows/build_release_template.yml

The DMD nightly build for FreeBSD fails since two weeks, because the old version is not available anymore. As a result the nightly builds for other platforms are also not uploaded.
This increases the versions for FreeBSD the same as in https://github.com/dlang/dmd/pull/15979, but I have not tested it.

Bump FreeBSD to 13.2

---

script/install.sh

This fixes the activate script when install.sh is called with a relative path (e.g. `install.sh -p .`).

Only use an absolute path in the activate script.

---

test/installation.sh

As time goes on, verifying these post build has ever diminishing returns.

test: Remove some EOL platforms

---

create_dmd_release/create_dmd_release.d

Caught by CI, which is currently red for stable.

[stable] Windows: Fix missing bin64\sc.ini

---

.github/workflows/build_release_template.yml

See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
This should fix a warning for the nightly builds in bugzilla issue 24600.

GHA: Replace deprecated set-output

---

.github/workflows/build_release_template.yml

Don't use the DMD `VERSION` file, currently leading to names like `dmd-v2.110.0-beta.1.exe`, which accumulate for the nightly release: https://github.com/dlang/dmd/releases/tag/nightly
Switch to `dmd-master.exe`, similar to the other artifact names.

CI: Rename Windows installer artifacts to dmd-<branch>.exe

---

create_dmd_release/create_dmd_release.d
linux/dmd_deb.sh
linux/dmd_rpm.sh
osx/Makefile

https://github.com/dlang/dmd/pull/20665 came back to bite me as the new release manager.

Remove copying of now deleted samples folder
