dlang/installer

create_dmd_release/create_dmd_release.d
- DOC and PHOBOSDOC are no longer required
=> fix building dman

create_dmd_release/build_all.d, create_dmd_release/create_dmd_release.d
=> support for host dmd compiler

osx/dmd2.conf, osx/post-install.sh
* Update dmd2.conf with new install location
* Use sudo for all commands in post install script
=> Followup for OS X installer not compatible with 10.11

windows/d2-installer-descriptions.nsh, windows/d2-installer.nsi
- detect missing VC/SDK before installation and offer to
start the VS2013 installation
=> ask to install missing VC/SDK for 64-bit support

create_dmd_release/build_all.d, create_dmd_release/common.d
- e.g. dmd.2.068.1.linux.tar.xz, dmd.2.068.1.windows.7z
- shrinks archives to ~50% of the zip size
=> create lzma compressed archives

README.md
https://issues.dlang.org/show_bug.cgi?id=14714
=> fix Issue 14714 - Add README.md to the Installer Repository

create_dmd_release/create_dmd_release.d
- remove dmd.conf before building dmd from host compiler
- also use dmd.conf target of posix.mak
=> fix issue - host compiler uses wrong dmd.conf

create_dmd_release/build_all.d
- still keep a copy as link.exe for now
=> rename link.exe to optlink.exe

create_dmd_release/build_all.d, create_dmd_release/patches/dlang.org.patch
- update dlang.org patch
- fix issue with newer openssl host library
=> update build scripts

linux/dmd_deb.sh, linux/dmd_rpm.sh
- don't symlink changelog into usr/share/doc/dmd
- it's odd to only have the changelog there
- version number (2.068.2.html) changes with every release
=> fix for separate changelogs

windows/d2-installer.nsi
needs https://github.com/D-Programming-Language/dmd/pull/5031
=> add support for VS2015 and Universal CRT

windows/d2-installer.nsi
also fix ${UCRTVersion} -> $UCRTVersion
=> do not skip VS detection when installing with /f

create_dmd_release/create_dmd_release.d
For https://github.com/D-Programming-Language/druntime/pull/1402
Untested.
=> create_dmd_release: Copy Win32 import libraries from Druntime

create_dmd_release/build_all.d, create_dmd_release/common.d
- download platform archives
- verify downloads
- no longer build combined zip
=> use platform specific archives

bootstrap/bootstrap-dmd.bat, create_dmd_release/build_all.d, linux/dmd_deb.sh, linux/dmd_phobos.sh, windows/d2-installer.nsi
update links to our new namespace :)
=> update links to dlang

script/install.sh
- silence output and just print path to the activate script
- useful for scripts to install and activate a compiler
=> add --activate option to install command

script/install.sh
- needed to fix Travis-CI, see https://github.com/travis-ci/travis-build/pull/717#issuecomment-216506801
=> workaround failing xz detection on OSX

create_dmd_release/build_all.d, create_dmd_release/create_dmd_release.d
- dub prereleases are only use for dmd
prereleases, not for nightlies and dmd releases
@s-ludwig
=> build dub with dmd releases

create_dmd_release/patches/dlang.org.patch
=> update dlang.org patch

script/install.sh
#186 added support for "ldc-beta".
=> [Trivial] Update command help for #186

script/install.sh
- should be a bit more reliable than ftp.digitalmars.com
=> get LATEST dmd version from S3

script/install.sh
- might fails as much as downloads
=> retry fetch to stdout operations

create_dmd_release/build_all.d
- fallback to master if a feature branch does not
exist in some of the dlang repos
@UplinkCoder
=> support building previews for feature branches

script/install.sh
- resolve nightlies.dlang.org/dmd-branch/LATEST to
e.g. dmd-branch-2016-10-21
- use branch in basename of file dmd.$branch.$os
=> support feature branch previews in install script

create_dmd_release/create_dmd_release.d
- the import through std.process is gone
=> replace C's system w/ spawnShell

create_dmd_release/build_all.d, create_dmd_release/patches/dlang.org.patch
- also skip cloning&patching dlang.org with --skip-docs
=> fix docs building

create_dmd_release/build_all.d, create_dmd_release/create_dmd_release.d, create_dmd_release/patches/dlang.org.patch
- change make target to all (default is 404.html :/)
- update patch to not fail without PHOBOS_STABLE_DIR
- install libcurl:i386 for dub
=> fix dlang.org docs build

windows/d2-installer.nsi
Cherry-picked https://github.com/dlang/installer/pull/227 due to http://forum.dlang.org/post/rslylrlbxddsrlkwmrwg@forum.dlang.org
=> add detection of VS 2017 [cherry-picked for stable]

script/install.sh
- reduce threat vector gdmd script manipulations
=> pin gdmd script version

create_dmd_release/build_all.d
- VERSION file was changed to include 'v' prefix
=> fix Issue 17614 - __VERSION__ has the wrong value

linux/dmd_deb.sh, linux/dmd_rpm.sh
=> remove dman from installers to workaround Issue 17731

windows/d2-installer-descriptions.nsh, windows/d2-installer.nsi
There is some breakage with VS2017 update 15.3.1, not sure that can be fixed before the release of dmd 2.076. That would mean another minor Visual D update.
=> update Visual D version and description

script/install.sh, travis.sh
- do an atomic mv to not change the currently executed script
=> fix in-place update of script

.codecov.yml
=> add codecov config file

create_dmd_release/create_dmd_release.d
=> gcstub was removed from druntime

create_dmd_release/build_all.d, create_dmd_release/create_dmd_release.d
- also install newer git version on Linux for tools/contributors.d
=> fix dmd build using generated/

README.md, script/install.sh
See also: https://dlang.org/install.html
=> Link to dlang.org/install.html

travis.sh
Simple test of printing __VERSION__ and comparing whether its the
correct frontend.
=> Add a sanity check to test successfull compiler installation

windows/build_lld.bat
see https://issues.dlang.org/show_bug.cgi?id=18509
=> build LLD against static VC runtime library

windows/build_mingw.bat
build mingw libraries into a mingw sub folder as expected by dmd
=> 18522 - [REG 2.079-b2] MinGW import libraries interfere with platform SDK

test/installation.sh
=> test beta and rpm installation on fedora, centos, and opensuse

script/install.sh
Bump to latest - see also: https://github.com/D-Programming-GDC/GDMD/commit/a67179d54611ae8cfb1d791cf7ab8e36c3224b76
=> Bump installer script hash

script/install.sh
see e.g. https://github.com/travis-ci/travis-ci/issues/9613
=> Use DUB GitHub binaries as the first dub download mirror

README.md
s.t. there's a slight chance that someone finds them.
=> Add links to the AppVeyor branches

create_dmd_release/create_dmd_release.d
To fix the nightlies: http://nightlies.dlang.org/dmd-master-2018-05-31/build.html
=> Use ENABLE_RELEASE=1 instead of the removed RELEASE=1

windows/d2-installer.nsi
@MartinNowak I hope this can still make it into the 2.081 release.
=> bump Visual D version to 0.47.0

create_dmd_release/build_all.d
See https://github.com/dlang/installer/pull/332
I named the zip file mingw-libs-5.0.2-1.zip, uploaded it and its signature to S3.
It looks like that's all that's needed.
=> Update mingw to 5.0.2-1

test/installation.sh
- overriable env variable still defaults to docker
=> allow to test installations with podman instead of docker

linux/dmd_deb.sh
The dmd-doc.desktop file is pointing to the wrong html doc page.
New Path: Exec=xdg-open usr/share/dmd/html/d/spec/spec.html
=> changed dmd-doc.desktop Exec line.

create_dmd_release/build_all.d
See https://github.com/dlang/installer/pull/351
=> Update to LLD 7.0.0

create_dmd_release/create_dmd_release.d
See https://github.com/dlang/druntime/pull/2438#issuecomment-477783864
=> Windows: fix quoting when building with win64.mak

appveyor.yml, windows/build_lld.bat
https://releases.llvm.org/8.0.0/tools/lld/docs/ReleaseNotes.html
=> Upgrade LLD to 8.0.0

changelog/lld-8.dd, create_dmd_release/build_all.d
Upgrade was done in https://github.com/dlang/installer/pull/374 and the artifact has been uploaded to S3.
=> Upgrade LLD to 8.0.0 [master]

test/installation.sh
- update debian to include buster
- drop debian:wheezy
- fix missing jessie-updates apt source for debian:jessie
- fix opensuse tumbleweed
=> update installation tests

script/install.sh, test/t/base.sh
https://github.com/dlang/installer/commit/42a3937b706db32bf9bf1ff887d93c1704a10798#r33502782
https://travis-ci.org/dlang/tools/jobs/532433843
CC @wilzbach , maybe you'd like to see if this fix is correct or add a test.
=> script/install.sh: Fix unbound variable error

windows/d2-installer.nsi
Looked pretty straight forward.
=> Installer updates: remove D1, update VisualD, rename Publisher

changelog/update-curl.dd, create_dmd_release/build_all.d
See also: https://github.com/dlang/installer/pull/399
=> Update curl to 7.65

script/install.sh
=> Remove unnecessary quotes.

.azure-pipelines/build-docs.yml, .azure-pipelines/build-winrelease.yml, azure-pipelines.yml, create_dmd_release/build_all.d, create_dmd_release/common.d, create_dmd_release/create_dmd_release.d, windows/EnvVarUpdate.nsh, windows/build_release.bat
to make the build process more visible and allow testing PRs to the installer
=> Add building windows installer to azure pipelines

create_dmd_release/build_all.d
From https://github.com/dlang/installer/pull/420 and https://github.com/dlang/installer/pull/418
=> Update curl to 7.68 and LLD to 9.0.0

create_dmd_release/build_all.d
See https://github.com/dlang/installer/pull/433
=> Use LLD with /SAFESEH:NO

windows/d2-installer.nsi
wait for uninstaller to terminate
As I cannot reproduce the issue locally, let's wait for the reporter to confirm it actually helps.
=> [WIP] fix Issue 20489 - Installer deleting files after install

changelog/lld-9.dd, changelog/mingw-6.dd, changelog/windows.dd
integrates the two separate existing changelog entries.
=> document changes to the Windows installation

.azure-pipelines/build-winrelease.yml, create_dmd_release/build_all.d, create_dmd_release/common.d, windows/build_release.bat
Let's see if the signatures can be verified on azure...
=> azure: do not skip verifying signatures of downloaded archives

create_dmd_release/codesign/sign.ps1, create_dmd_release/create_dmd_release.d
- fix dub build
- fix usage of correct vsvarsall env
- fix codesign script
=> fixups for VS2017

create_dmd_release/build_all.d
@MartinNowak this update is still missing
=> install mingw-7.0.0-3.zip to add msvcr120.dll as mentioned in the changelog

create_dmd_release/build_all.d, create_dmd_release/create_dmd_release.d
`create_dmd_release` was not working with the right clones directory, causing confusing git behaviour.
=> Fix CI checks.

script/install.sh
see https://github.com/dlang/dlang.org/commit/b4c3ae33c14986a620ea500d3d12c3df41403292
=> install.sh: update help() mesage

create_dmd_release/build_all.d, create_dmd_release/create_dmd_release.d
This reverts commit 5da43299a9ed308d628ef20cb1c39980afe83354, reversing
changes made to b4b6697017b6c6942437d8fa8922366677a7edc0.
See https://github.com/dlang/installer/pull/452#issuecomment-647037588
=> Revert "Merge pull request #452 from veelo/fix_CI"

script/install.sh
- Fixes issue 21059.
- script/install.sh: Provide a default fallback
=> merge stable

script/install.sh
This reverts commit 41a1da1de15ea6250b88ef953ff5ff2891164986.
=> Revert "add auto-update for the d-keyring (#457)"

create_dmd_release/build_all.d
GitHub's API sometimes rejects the request which fetches the available
tags with a `HTTP 403`. This patch uses `git ls-remote` as a fallback
when the current tag could not be retrieved from the API.
=> build_all.d: Use git ls-remote as a fallback in getDubTag

azure-pipelines.yml, script/install.sh
This fixes the installer script for Apple M1 MacBooks, fixing issue https://issues.dlang.org/show_bug.cgi?id=22078.
Also see https://github.com/dlang/tools/pull/441 for a similar fix.
=> Fix for LDC arm64 build

script/install.sh
See also:
https://issues.dlang.org/show_bug.cgi?id=22078
https://github.com/dlang/installer/pull/488
@lionello @maxhaton @jacob-carlborg
=> Improve install.sh on macOS with arm64 architecture.

create_dmd_release/create_dmd_release.d, test/release/validate_release.sh
The file was added in the meantime
=> Remove workaround for missing dmd/win64.mak

changelog/VisualDUpdate.dd, windows/d2-installer.nsi
=> Nobody has routinely updated Visual D for 3 years

changelog/issue_23623.dd, windows/d2-installer.nsi
Fixes https://issues.dlang.org/show_bug.cgi?id=23623
=> Prefer 64 bit over 32 bit DMD on Windows 64 bit.

.github/workflows/build_release_template.yml, .github/workflows/test_release.yml
=> CI: Migrate from vmactions/freebsd-vm action to cross-platform-actions/action

create_dmd_release/build_all.d, create_dmd_release/create_dmd_release.d, create_dmd_release/extras/windows/dmd2/windows/bin/README.TXT
Bundling it in is no longer necessary.
=> Remove all references to optlink

.github/workflows/build_release_template.yml, create_dmd_release/common.d, test/release/validate_release.sh
The nightlies are broken since March 6th...
=> [stable] Fix CI incl. nightly DMD builds

.github/workflows/build_release_template.yml, .github/workflows/build_windows.yml, create_dmd_release/create_dmd_release.d, test/release/validate_release.sh, windows/build_curl.bat, windows/build_lld.bat, windows/build_mingw.bat
[I've only tackled Windows too because CI here has shown that there's a brown-out of windows-2019 today...]
=> [stable] Fix FreeBSD build and prepare Windows for upcoming drop of windows-2019 image
